version: '3.9'

services:
  web:
    build: .
    ports:
      - 8080:8080
    depends_on:
      - db
    environment:
      - FLASK_ENV=development
    volumes:
      - .:/app
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydatabase
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - 5432:5432

volumes:
  pgdata:
